### ISSUE TITLE
Default implementation of actionButtonPressed is unreachable

### ISSUE THREAD

**Issue by weakfl** [younatics/MediaBrowser#22]
In `MediaBrowser.swift`, line 2053
```swift
if let d = delegate {
    d.actionButtonPressed(at: currentPageIndex, in: self, sender: sender)
    return
}
```

The function will always return here, since the delegate should be set.
You should probably change the protocol extension to initiate the default behaviour (show UIActivityViewController) and just call it.

**Comment by younatics** [comment]
Could you send me PR?

**Comment by weakfl** [comment]
See #27.
This also fixes a crash when saving images on iOS 11.

**Comment by younatics** [comment]
Thanks! Please see latest release 👍
