### ISSUE TITLE
Toolbar transparency isn't working

### ISSUE THREAD

**Issue by weakfl** [younatics/MediaBrowser#23]
You need to provide empty Images for transparency to work. In `MediaBrowser.swift`, lines 368 and 369:
```swift
toolbar.setBackgroundImage(UIImage(), forToolbarPosition: .any, barMetrics: .default)
toolbar.setBackgroundImage(UIImage(), forToolbarPosition: .any, barMetrics: .compact)
```

See Apple's [documentation](https://developer.apple.com/documentation/uikit/uitoolbar/1618001-translucent) for details.
Changing the `alpha` of the toolbar will also change the alpha of the controls, which is undesirable imho.

**Comment by younatics** [comment]
This will be updated in next version. Thanks!
