### ISSUE TITLE
[request] Change Media access level to open

### ISSUE THREAD

**Issue by weakfl** [younatics/MediaBrowser#24]
Would you mind changing the access level of the `Media` class to `open`?

I'd like to use your library in a project with some legacy objective-c code. Writing a wrapper class was straight forward, however, I'd need to subclass `Media` to make it work.

Of course I could fork, but would prefer no to...

**Comment by younatics** [comment]
Please see latest version :) 

Thanks!

**Comment by weakfl** [comment]
Thanks!
But it seems you also need to add `@objcMembers` to make it work, please see my pr #25
