### ISSUE TITLE
Crash if loading progress is infinite

### ISSUE THREAD

**Issue by weakfl** [younatics/MediaBrowser#31]
See #30 

It actually crashes in `UICircularProgressRing`, but imho you should avoid passing infinite values to `UICircularProgressRing` anyway.

**NOTE:** It might be more appropriate to use `min(0, CGFloat(receivedSize)/CGFloat(expectedSize))`, I didn't really investigate the actual values. But I guess `expectedSize` was zero when it crashed...

**Comment by younatics** [comment]
I did it. Thanks!
