### ISSUE TITLE
Carthage compatibility

### ISSUE THREAD

**Issue by josjevv** [younatics/MediaBrowser#37]
Has anyone got this to work using Carthage?

There is no Cartfile in the project for `SDWebImage` and `UICircularProgressRing`. Adding these frameworks to the project's Cartfile (as documented) results in build errors like these:
```
/Users/josvanvelzen/projects/socialschools-ios/Carthage/Checkouts/MediaBrowser/MediaBrowser/MediaZoomingScrollView.swift:10:8: error: no such module 'UICircularProgressRing'
import UICircularProgressRing
       ^
```

also, in the build phases there is a hard dependency to CocoaPods 
```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/josvanvelzen/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MediaBrowser/2.0.6/Build/Intermediates.noindex/ArchiveIntermediates/MediaBrowser/IntermediateBuildFilesPath/MediaBrowser.build/Release-iphoneos/MediaBrowser.build/Script-0C26AE7EAC3BB33AE3116C77.sh
    cd /Users/josvanvelzen/projects/socialschools-ios/Carthage/Checkouts/MediaBrowser
    /bin/sh -c /Users/josvanvelzen/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MediaBrowser/2.0.6/Build/Intermediates.noindex/ArchiveIntermediates/MediaBrowser/IntermediateBuildFilesPath/MediaBrowser.build/Release-iphoneos/MediaBrowser.build/Script-0C26AE7EAC3BB33AE3116C77.sh
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I am no expert in this, I added the Cartfile in the `Carthage/Checkouts/MediaBrowser` which does resolve the dependencies but I probably will still have to link to frameworks somehow. 

Has anyone got this to work using carthage only?

**Comment by mnvr** [comment]
> Has anyone got this to work using carthage only?

Yes. See https://github.com/younatics/MediaBrowser/pull/42.

**Comment by younatics** [comment]
See latest version! Thanks!

**Comment by mnvr** [comment]
Actually, it got broken again because when you did the release, the Pod changes came back
(https://github.com/younatics/MediaBrowser/commit/43e30b14fb4fc34df1a62c7b9d062dfc72df08fd#diff-f9fcf3810a370c4640c4d55b38542be6R10)

As I mentioned in my PR message, I don't see an easy way of modifying the project to support both Carthage and CocoaPods at the same time.
