### ISSUE TITLE
Issue with Selection and Action button together

### ISSUE THREAD

**Issue by TomMajor** [younatics/MediaBrowser#38]
Hi younatics,

thanks for a great media browser, I came here from MWPhotoBrowser, which is not maintained anymore, and I like your project.

I need the selection feature and the action button together in use case "Photo selection grid".
If I do this, the action button moves to the upper right corner and hides the "Done" button and its function.
I did a quick fix for this, commenting this line out in updateNavigation():
`self.navigationItem.rightBarButtonItem = ab`

which fixes the issue.
Could you please maybe add an extra option / public setter for this case, or do you accept a pull request for this? My fix workes for me, but want to stay in sync with this repo for further updates.

---

Also, another minor issue:
If I tap a photo in the grid, the blue selection image is briefly show all though the photo was not selected, while the grid view is animating out.
I debugged this and found out it seems to happen below this line, in the animation:
`// Animate, hide grid and show paging scroll view`

Can you think of a way to fix this?

Thanks,

**Comment by younatics** [comment]
Sure you can make PR!

**Comment by TomMajor** [comment]
ok, just made a PR for fixing the action button issue in a photo selection grid.

**Comment by younatics** [comment]
Thanks!
