### ISSUE TITLE
Trying to Render Grid Gallery View in Swipe Tab View...

### ISSUE THREAD

**Issue by iunicron** [younatics/MediaBrowser#4]
![screen shot 2017-09-20 at 3 31 05 pm](https://user-images.githubusercontent.com/31723529/30639541-c633a1e2-9e18-11e7-94fc-706ba49a2d16.png)

I have tabs, as you can see in the screenshot, and i am trying to initiate the gallery in the tabs views without making it go full screen. I think i need help.

<img width="974" alt="screen shot 2017-09-20 at 3 32 51 pm" src="https://user-images.githubusercontent.com/31723529/30639643-24375e6e-9e19-11e7-84d5-21864543e5e4.png">
Here is my source code for it

PS: Need Help...?

**Comment by jegumhon** [comment]
As you know, MediaBrowser is basically a UIVIewController.
So, if you don't use AutoLayout or any manipulation of frame size, 
MediaBrowser will be presented in the same size with UIScreen's frame.

So, consider to use Autolayout or maniplate manually view's frame size, plz.

And in your case, I think you should use container view controller like below blog.
https://naveenr.net/beginning-container-views-in-ios/

**Comment by younatics** [comment]
Please reopen this issue if you have more questions. Thanks!
