### ISSUE TITLE
Something about the license

### ISSUE THREAD

**Issue by JackLauu** [younatics/MediaBrowser#47]
Hello, Seungyoun Yi. Thanks for your project, I will use it in my close-source app. I have a question about the copyright about the image resources in your project. First of all, could I use the interface icons directly in my app or should I design and replace them all? Secondary, could I use those beautiful pictures in the demo? 

I don't know the source of those pictures and icons and care about their copyright. Wish you give me some advice and reply. Thank you.

Also, I want to know if Mit license or other code license like Apache license still work for image resources?

**Comment by younatics** [comment]
Hello~
Feel free to use those images. I got those images in free website. 
You can use icons too. My friend made it for me :)
Thanks!

p.s. plz tell me application that you use this lib if you don't care :)

**Comment by JackLauu** [comment]
ok, thanks for your reply.
