### ISSUE TITLE
Done button in video iPhone x is overlapping with the status bar

### ISSUE THREAD

**Issue by HudaElhady** [younatics/MediaBrowser#48]
Done button in video iPhone x is overlapping with the status bar
![simulator screen shot - iphone x - 2018-03-13 at 14 31 41](https://user-images.githubusercontent.com/10253129/37341790-56329d26-26cb-11e8-8fe5-634e5078b6be.png)

**Comment by younatics** [comment]
Please check this issue in new version. Thanks!
