### ISSUE TITLE
fatal error: Can't form Range with upperBound < lowerBound

### ISSUE THREAD

**Issue by iunicron** [younatics/MediaBrowser#5]
<img width="868" alt="screen shot 2017-09-20 at 5 48 54 pm" src="https://user-images.githubusercontent.com/31723529/30644534-1ab97c7e-9e2c-11e7-9655-f18df6a61a7c.png">

Found another bug i think so.. when loading data from a JSON request.

I am using ALAMOFIRE...

<img width="736" alt="screen shot 2017-09-20 at 5 50 27 pm" src="https://user-images.githubusercontent.com/31723529/30644575-377328c4-9e2c-11e7-9565-23264e1e3f60.png">

Screenshot of Alamofire Code

**Comment by younatics** [comment]
Hello @iunicron,
I published 1.0.1 with defense code.
Please try it.

Thanks!
