### ISSUE TITLE
No doneButton (rightBarButtonItem)

### ISSUE THREAD

**Issue by anastasioscho** [younatics/MediaBrowser#54]
If there are no images then the doneButton does not appear.

I used a simple setup:

let photoBrowser = MediaBrowser(delegate: self)
photoBrowser.enableGrid = true
photoBrowser.startOnGrid = true
present(UINavigationController(rootViewController: photoBrowser), animated: true, completion: nil)

**Comment by younatics** [comment]
please check this issue in new version.
Thanks!
