### ISSUE TITLE
Questions regarding using MediaBrowser with firebase

### ISSUE THREAD

**Issue by jpowang** [younatics/MediaBrowser#6]
Currently, my backend is supported by firebase, which is an cloud-hosted database that queries asynchronously. Currently it fetchs the list of picture urls from firebase. With the example provided in MediaBrowserSample, it seems like the number of pictures need to be predetermined before calling the browser or exception will be thrown. Is there any workaround on that? To display the pictures correctly while still fetching the data in the backend?

**Comment by younatics** [comment]
Hmm.. I can understand your situation, but I don't know how to achieve this situation. Could you tell me more about this?

**Comment by younatics** [comment]
There is now no reply for this issue, please reopen this issue again.
