### ISSUE TITLE
Caption not showing on iPhone X

### ISSUE THREAD

**Issue by skercher** [younatics/MediaBrowser#65]
Hi, Great library!  I see one issue where the caption is not showing on the bottom bar on the iPhone X.

<img width="378" alt="screen shot 2018-12-27 at 10 20 50 am" src="https://user-images.githubusercontent.com/24554/50488902-f2e5df00-09c1-11e9-8e00-35b297dcb3ca.png">

**Comment by sandeepsuthar** [comment]
I am also facing this issue. Caption view behind the Toolbar on Iphone X

**Comment by younatics** [comment]
hello @skercher ,
2.3.0 version is released✨
Please check this issue in new version!
