### ISSUE TITLE
Issues leveraging MediaBrowser in Objective C app

### ISSUE THREAD

**Issue by philchristensen** [younatics/MediaBrowser#67]
I've been working on getting MediaBrowser properly installed in my application, which is an Objective C app from 2013 that I've been updating for the latest OS, iPhone, etc.

I had to make a few minor changes to the library (submitted as a PR) to get it to be available to my Objective C code, but overall everything is working pretty well. I just have a couple issues I'm looking for help with.

1. For some reason, the grid button on the bottom nav bar seems to be inconsistent as to whether it appears or not. I've seen it display properly once, but I can't get it to happen again. I've tried forcing the enableGrid property, but to no avail.
2. The second issue is related to video assets when paging through the browser. From the demo it looks like there's supposed to be a play button overlay; in my app the poster image of the video appears and is properly tappable, but it shows no indication of that.

I've gone through the demo app in some detail, but I can't see anything special that needs to be done to enable either of these features, so I assume it must be an issue between ObjC and Swift. Any guidance in this issue would be greatly appreciated.

**Comment by younatics** [comment]
please check this issue in new version.
Thanks!
