### ISSUE TITLE
Can't get it to work in ObjC Project

### ISSUE THREAD

**Issue by anonymouz4** [younatics/MediaBrowser#72]
I've tried days to get it to work but just can't figure it out. If I link the framework, the app crashes.
If I however link it as optional instead of required, I can run it but every Object in the Framework is always `nil`. (For example `[[Media alloc] init]` always returns `nil`)

In the Issues section, I've seen that others went through this too. Does anyone have an idea?

**Comment by younatics** [comment]
hello @anonymouz4 ,
2.3.0 version is released✨
Please check this issue in new version!
