### ISSUE TITLE
Grid view image not loading

### ISSUE THREAD

**Issue by ronak4567** [younatics/MediaBrowser#84]
I have to start mediabrowser with GridView and do this code Swift 5
Single image show but in grid view it's not showing

```
let browser = MediaBrowser(delegate: self);
      
        browser.zoomPhotosToFill = true;
        browser.alwaysShowControls = true;
        browser.enableGrid = true;
        browser.startOnGrid = false;

        self.present(browser, animated: true) {

        }
```
MediaBrowserDelegate
```
func numberOfMedia(in mediaBrowser: MediaBrowser) -> Int {
        return self.arrGaller.count
    }
    
    func media(for mediaBrowser: MediaBrowser, at index: Int) -> Media {
        if index < arrGaller.count {
          return arrGaller[index]
        }
        return Media(image: UIImage(named: "logo")!)
    }
    
```

![Simulator Screen Shot - iPhone 6s - 2020-07-08 at 18 41 44](https://user-images.githubusercontent.com/23085409/86922792-c419fe80-c14a-11ea-876e-58ff7deb1cc6.png)
![Simulator Screen Shot - iPhone 6s - 2020-07-08 at 18 41 50](https://user-images.githubusercontent.com/23085409/86922802-c8461c00-c14a-11ea-9f31-ead022a17596.png)

**Comment by ardaegeunlu** [comment]
Have you resolved this issue? I am looking for a web-photo grid solution too.

**Comment by ardaegeunlu** [comment]
Found the solution. Just implement this function in the delegate to have thumbnails

 func thumbnail(for mediaBrowser: MediaBrowser, at index: Int) -> Media
